name: ocr-vqgan
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - torchmetrics==0.6.0
    - wandb==0.13.4
    - SSIM-PIL
    - torch-fidelity
    - -e .
